spring:
  application:
    name: aws-bedrock-chat-journal
  jackson:
    serialization:
      indent-output: true

server:
  port: 8080

app:
  aws:
    region: us-east-1
    default-model-id: amazon.nova-lite-v1:0
  storage:
    sessions-directory: data/sessions
  limits:
    max-messages-per-session: 100
  inference:
    temperature: 0.7
    top-p: 0.9
    max-tokens: 512
  logging:
#    bedrock-payload-mode: off
    bedrock-payload-mode: raw
    redact-bedrock-content: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{requestId}] %logger{36} - %msg%n"
  level:
     net.jrodolfo.aws.bedrock.chat.journal.bedrock.payload: DEBUG

# Example local debugging settings:
# logging:
#   pattern:
#     console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{requestId}] %logger{36} - %msg%n"
#   level:
#     net.jrodolfo.aws.bedrock.chat.journal: DEBUG
#     net.jrodolfo.aws.bedrock.chat.journal.bedrock.payload: DEBUG
#     software.amazon.awssdk: INFO
# app:
#   logging:
#     bedrock-payload-mode: summary
#     redact-bedrock-content: true
